version: "3.7"

services:
  servicer:
    container_name: servicer
    build:
      context: .
    restart: unless-stopped
    ports:
    - 5001:5000
    networks:
      hostnet: {}
    volumes:
    - .:/opt/servicer
  
  async_servicer_trigger:
    container_name: async_servicer_trigger
    build:
      context: ./build_async_servicer_trigger
    restart: unless-stopped
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: fylr_fylr

